apiVersion: iam.minio.upbound.io/v1alpha1
kind: GroupPolicy
metadata: {}
spec:
  deletionPolicy: string
  forProvider:
    group: string
    policy: string
  managementPolicy: string
  providerConfigRef:
    name: string
    policy:
      resolution: string
      resolve: string
  providerRef:
    name: string
    policy:
      resolution: string
      resolve: string
  publishConnectionDetailsTo:
    configRef:
      name: string
      policy:
        resolution: string
        resolve: string
    metadata:
      annotations:
      labels:
      type: string
    name: string
  writeConnectionSecretToRef:
    name: string
    namespace: string
status:
  atProvider:
    group: string
    id: string
    policy: string
  conditions:
  - lastTransitionTime: string
    message: string
    reason: string
    status: string
    type: string
